version: '3.8'

services:
  Api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  
  UI:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"