name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  SWA_build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy SWA to Azure
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'magedragheb/todocontainerapp/UI'
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_MUSHROOM_097CDAA1E }}
          repo_token: ${{ secrets.GHTOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_api_build: true
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "UI" # App source code path
          output_location: "UI/wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

