name: Docker Image CI
on:
  push:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
  packages: write
env:
  repo: magedragheb/todocontainerapp
jobs:
  DockerBuild-GHContainerReg-DeployAzureContainerApps:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHTOKEN }}
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Api to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:Api"
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.repo }}/api:${{ github.sha }}
          labels: |
            repo=${{ github.repository }}
            branch=${{ github.ref_name }}
            commit=${{ github.sha }}
      - name: Build and push UI to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:TodoBlazorServer"
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.repo }}/uiserver:${{ github.sha }}
          labels: |
            repo=${{ github.repository }}
            branch=${{ github.ref_name }}
            commit=${{ github.sha }}
      - name: Deploy Api to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/${{ env.repo }}/api:${{ github.sha }}
          registryUrl: ghcr.io
          registryUsername: ${{ github.repository_owner }}
          registryPassword: ${{ secrets.GHTOKEN }}
          resourceGroup: CourseEngineTesting
          location: switzerlandnorth
          containerAppEnvironment: todoapp-env
          containerAppName: todoapi
      - name: Deploy UI to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/${{ env.repo }}/uiserver:${{ github.sha }}
          registryUrl: ghcr.io
          registryUsername: ${{ github.repository_owner }}
          registryPassword: ${{ secrets.GHTOKEN }}
          resourceGroup: CourseEngineTesting
          location: switzerlandnorth
          containerAppEnvironment: todoapp-env
          containerAppName: todoui
