name: Docker Image CI

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Api to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:Api"
          file: Dockerfile
          push: true
          tags: ghcr.io/todocontainerapp/api:${{ github.sha }}
          labels: |
            repo=${{ github.repository }}
            commit=${{ github.sha }}
            branch=${{ github.ref_name }}

      - name: Build and push UI to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:UI"
          file: Dockerfile
          push: true
          tags: ghcr.io/todocontainerapp/ui:${{ github.sha }}
          labels: |
            repo=${{ github.repository }}
            commit=${{ github.sha }}
            branch=${{ github.ref_name }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Api to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/todocontainerapp/api:${{ github.sha }}
          resourceGroup: CourseEngineTesting
          containerAppName: todoapi

      - name: Deploy UI to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/todocontainerapp/ui:${{ github.sha }}
          resourceGroup: CourseEngineTesting
          containerAppName: todoui
