name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - { name: Api, dockerfile: Api/Dockerfile }
          - { name: UI, dockerfile: UI/Dockerfile }
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.project.name }}
          file: ${{ matrix.project.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.project.name }}:${{ github.sha }}
          labels: |
            repo=${{ github.repository }}
            commit=${{ github.sha }}
            branch=${{ github.ref_name }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Api to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/${{ github.repository }}/api:${{ github.sha }}
          resourceGroup: CourseEngineTesting
          containerAppName: todoapi

      - name: Deploy UI to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/${{ github.repository }}/ui:${{ github.sha }}
          resourceGroup: CourseEngineTesting
          containerAppName: todoui
