name: Azure SWA Build and Publish
on:
  push:
    branches:
      - "?"
jobs:
  SWA-Build-Publish:
    runs-on: ubuntu-latest
    name: Build and Publish to Azure Static Web Apps
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          action: "upload"
          app_location: "UI"
          output_location: "wwwroot"
