name: Test CI
on:
  push:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
  packages: write
env:
  COMMIT_SHA: $(git rev-parse --short ${{ github.sha }})
  REPO: magedragheb/todocontainerapp
  registry: todocontainer.azurecr.io
jobs:
  AzureLogin:
    name: Azure Login
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  BuildPushApi:
    name: Build Api and push to azurecr
    needs: AzureLogin
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Api to Azure Container Registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:Api"
          file: Dockerfile
          push: true
          tags: ${{ env.registry }}/${{ env.REPO }}/api:${{ env.COMMIT_SHA }}
          labels: |
            repo=${{ github.repository }}
            branch=${{ github.ref_name }}
            commit=${{ github.sha }}
  BuildPushUI:
    name: Build UI and push to azurecr
    needs: AzureLogin
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push UI to Azure Container Registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:UI"
          file: Dockerfile
          push: true
          tags: ${{ env.registry }}/${{ env.REPO }}/ui:${{ env.COMMIT_SHA }}
          labels: |
            repo=${{ github.repository }}
            branch=${{ github.ref_name }}
            commit=${{ github.sha }}
  DeployApi:
    name: Deploy Api to Azure Container Apps
    needs: BuildPushApi
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Api to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.registry }}/${{ env.REPO }}/api:${{ env.COMMIT_SHA }}
          resourceGroup: CourseEngineTesting
          location: italynorth
          containerAppName: todoapi
  DeployUI:
    name: Deploy UI to Azure Container Apps
    needs: BuildPushUI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy UI to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.registry }}/${{ env.REPO }}/ui:${{ env.COMMIT_SHA }}
          resourceGroup: CourseEngineTesting
          location: italynorth
          containerAppName: todoui
