name: Test CI
on:
  push:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  AzureLogin:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: |
            COMMIT_SHA=$(git rev-parse --short ${{ github.sha }})
            echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
            echo "COMMIT_SHA=$COMMIT_SHA"
    